import { GoogleGenAI, Modality } from "@google/genai";

const fileToGenerativePart = (file: File) => {
  return new Promise<{ mimeType: string; data: string }>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result !== 'string') {
        return reject(new Error('Failed to read file as string'));
      }
      const result = reader.result.split(',')[1];
      resolve({
        mimeType: file.type,
        data: result,
      });
    };
    reader.onerror = (err) => reject(err);
    reader.readAsDataURL(file);
  });
};

export const generateTryOnImage = async (
  personImage: File,
  productImages: File[]
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const personPart = await fileToGenerativePart(personImage);
  const productParts = await Promise.all(productImages.map(fileToGenerativePart));

  const textPrompt = {
    text: `**Task: Image Editing - Virtual Try-On**

You are a highly precise, automated photo editor. Your ONLY function is to superimpose fashion items onto an existing photograph of a person.

**Input:**
- **Image 1 (Primary Canvas):** A photo of a person. THIS IMAGE MUST NOT BE CHANGED.
- **Image 2+ (Items):** Photos of clothing, accessories, etc.

**CRITICAL, UNBREAKABLE RULES:**

1.  **IDENTITY PRESERVATION (MANDATORY):**
    - The person in the primary canvas image—including their face, facial features, expression, hair, skin tone, body shape, and pose—MUST be preserved with 100% accuracy.
    - It is ABSOLUTELY FORBIDDEN to generate a new face, alter the face, or replace the person. The output person must be IDENTICAL to the input person.

2.  **BACKGROUND INTEGRITY (MANDATORY):**
    - The background of the primary canvas image MUST remain completely unchanged. Do not add, remove, or modify any part of the background.

3.  **YOUR ONLY TASK:**
    - Your sole responsibility is to realistically place the provided fashion items (Image 2+) onto the person in the primary canvas (Image 1).
    - Adapt the items to fit the person's pose, but DO NOT adapt the person to fit the items.

**Final Output Requirement:**
- The final output must be the ORIGINAL primary canvas image, modified ONLY by the addition of the fashion items. Any output that shows a different person or background is a failure.`
  };

  const imageParts = [
    { inlineData: personPart },
    ...productParts.map(part => ({ inlineData: part }))
  ];

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [ ...imageParts, textPrompt ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    throw new Error('No image was generated by the AI.');
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    throw new Error("Failed to generate AI try-on image.");
  }
};